### ISSUE TITLE
Would you like to add other transform support?

### ISSUE THREAD

**Issue by StageGuard** [Qufyy/obs-scale-to-sound#3]
Since this plugin allows component size changes based on audio wave, I think you can add more transform styles like translation, rotation or color changes, etc..

**Comment by Qufyy** [comment]
You can use this https://obsproject.com/forum/resources/move-transition.913/ to make anything react to sound. It has a filter called "Audio Move" that you put on audio sources and can change anything you want

**Comment by StageGuard** [comment]
thank you for replying
