### ISSUE TITLE
Scale not working with virtual audio device

### ISSUE THREAD

**Issue by ASchneiderBR** [Qufyy/obs-scale-to-sound#4]
Hello @Qufyy, first of all, thanks for creating this great plugin :)

I've noticed that scaling down to 0% using a virtual audio device, here's a video showing what I mean (watch for the `TTS voice` audio input in the mixer):

https://user-images.githubusercontent.com/25224882/155521656-0fdeee5c-35b4-4273-b01b-5b892c7a222a.mp4

This does not happens with my mic, when I stop talking, using those settings, the image disappears (0% scale).

Thank you!

**Comment by Qufyy** [comment]
This is happening because some audio sources don't send any data when they're completely silent, while others do. I'm working on it right now

**Comment by Qufyy** [comment]
Fixed in [1.2.1](https://github.com/Qufyy/obs-scale-to-sound/releases/tag/1.2.1)

**Comment by ASchneiderBR** [comment]
Wow! That was fast hahah Thanks a lot for the fix, working great now :)
